version: 0.1

<<<<<<< HEAD
environmental_variables:
  palintext:
=======
environment_variables:
  plaintext:
>>>>>>> demo
    phase: "alpha"

phases:
  pre_build:
    commands:
      - mvn clean
  build:
    commands:
      - mvn package
artifacts:
  files:
    - target/quickbucks.war
  discard-paths: yes
