version: 0.1

environment_variables:
  plaintext:
    phase: "alpha"

phases:
  pre_build:
    commands:
      - mvn clean
  build:
    commands:
      - mvn package
artifacts:
  files:
    - quickbucks.war
  discard-paths: yes
